apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    name: result-app-pod
    app: voting-app
spec:
  containers:
  - name: result-app-pod
    image: kodekoud/examplevotingapp_result:v1
    ports:
      - containerPort: 80
