apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app: myapp-service
    type: service
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008
