apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    name: postgres-service
    app: voting-app
spec:
  selector:
    name: postgres-pod
    app: voting-app
  ports:
  - port: 5432
    targetPort: 5432
